CREATE DATABASE ECOMMERCE DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;;


USE ECOMMERCE;


CREATE TABLE COMPTE (
	IDCompte INT AUTO_INCREMENT,
	NomFamille VARCHAR(50) NOT NULL,
	Prenom VARCHAR(50) NOT NULL,
	Mail VARCHAR(70) NOT NULL,
	Adresse VARCHAR(100) NOT NULL,
	MotDePasse VARCHAR(255) NOT NULL,
	Date_Creation DATETIME NOT NULL,
	UNIQUE (Mail),
	PRIMARY KEY (IDCompte)
) ENGINE=InnoDB;


CREATE TABLE COMMANDE (
	IDCommande INT AUTO_INCREMENT,
	Date_Commande DATETIME NOT NULL,
	IDCompte INT NOT NULL,
	PRIMARY KEY (IDCommande),
	FOREIGN KEY (IDCompte) REFERENCES COMPTE(IDCompte)
)ENGINE=InnoDB;


CREATE TABLE PRODUITS (
	IDProduits INT AUTO_INCREMENT,
	Nom VARCHAR(50) NOT NULL,
	Prix DECIMAL(10,2) NOT NULL,
	Description VARCHAR(200) NOT NULL,
	PRIMARY KEY (IDProduits)
) ENGINE=InnoDB;


CREATE TABLE CONTENIR (
	IDCommande INT NOT NULL,
	IDProduits INT NOT NULL,
	PRIMARY KEY (IDCommande, IDProduits),
	FOREIGN KEY (IDCommande) REFERENCES COMMANDE(IDCommande) ON DELETE CASCADE,
	FOREIGN KEY (IDProduits) REFERENCES PRODUITS(IDProduits) ON DELETE CASCADE
) ENGINE=InnoDB;



